# Generated by Django 4.1.4 on 2022-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elec', '0002_alter_department_course_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
